#!/bin/sh
# Fetch freely licensed films to preview scores against.
#
#   sh hack/fetch-test-videos.sh ~/componium-media
#
# These are not committed. They are about 110MB together, they never change,
# and a repository is the wrong place for them. This script exists so getting
# them back is one command.
#
# Licences, both permissive enough to redistribute, which is why these two:
#
#   Crab Dance          Public Domain Mark 1.0
#                       https://archive.org/details/crab-dance
#   Big Buck Bunny      Creative Commons Attribution 3.0, Blender Foundation
#                       https://archive.org/details/BigBuckBunny_124
#
# Big Buck Bunny is the more useful of the two for this project: it has real
# scene structure, quiet stretches, and a couple of genuinely loud moments,
# which is exactly what the analysis engine is trying to find. Crab Dance is
# short, garish and relentless, which makes it a good test of the rest budget.
set -eu

DIR="${1:-$HOME/componium-media}"
mkdir -p "$DIR"

fetch() {
  name="$1"
  url="$2"
  out="$DIR/$name"
  if [ -f "$out" ]; then
    echo "have $name"
    return 0
  fi
  echo "fetching $name"
  # --location because archive.org redirects to whichever node holds the file.
  # -C - so an interrupted download resumes rather than starting again.
  curl -fSL -C - -o "$out.part" "$url"
  mv "$out.part" "$out"
}

fetch "crab-dance.mp4" \
  "https://archive.org/download/crab-dance/crab%20dance.ia.mp4"

fetch "big-buck-bunny.mp4" \
  "https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4"

cat > "$DIR/LICENCES.txt" <<'TXT'
Films in this directory are not part of Componium and are not covered by its
licence. They are here to test against.

crab-dance.mp4
    Public Domain Mark 1.0
    https://archive.org/details/crab-dance

big-buck-bunny.mp4
    Creative Commons Attribution 3.0
    (c) copyright Blender Foundation | www.bigbuckbunny.org
    https://archive.org/details/BigBuckBunny_124

componium-testclip.mkv, componium-subbed.mkv, componium-dynamics.mkv
    Generated by hack/make-testclips.sh and hack/make-dynamics-clip.sh.
    Synthetic, no rights attached.
TXT

echo
ls -la "$DIR"
